build: :sparkles: Introduce typescript
sechaba-mache/Flight-tracker pull request #5
Opened 2023-02-27 05:28 UTC by sechaba-mache

2023-02-27 07:49 UTC, kphutiyagae approved these changes

2023-02-28 04:51 UTC, MihlaliMgwebi requested changes
Add dist folder to your gitignore.
 
Including the "dist" folder in the repository can cause a number of issues such as bloating the size of the repository, making it slower to clone and download, and making it more difficult to manage changes and version control.

2023-03-02 06:34 UTC, sechaba-mache commented
> Add dist folder to your gitignore.
> 
> Including the "dist" folder in the repository can cause a number of issues such as bloating the size of the repository, making it slower to clone and download, and making it more difficult to manage changes and version control.

Done, added build and .DS_Store as well

2023-03-02 10:01 UTC, MihlaliMgwebi commented on .gitignore
> +dist
Great

2023-03-02 10:02 UTC, MihlaliMgwebi approved these changes

2023-03-02 10:04 UTC, sechaba-mache commented on .gitignore
> +dist
 👍🏽

2023-03-02 17:44 UTC, merged